### ISSUE TITLE
Question about Android -usage due to LGPL

### ISSUE THREAD

**Issue by dertom95** [AerialX/openal-soft-android#1]
Hi AreialX,
first thanks a lot for improving android-openal-soft that much. It works great.
This post is actually not an issue but more a question how you would advice how to
use openal-soft for android. Due to its LGPL-License you have to link dynamically (ok
that is done) and make it possible for users to switch the library to one of their wish.
And this point makes be headaches. I thought I found the solution but that actually needs
a rooted device. 
Any suggestion?

Thanks a lot,Tom

**Comment by AerialX** [comment]
While it's true that the easiest way to swap out the library is to root your device, I don't really see that as an issue. That's just a side-effect of the way it's installed: installing an LGPL library on a normal machine usually results in it residing in a path that only the system's root/admin user can modify.

As far as I'm concerned using normal Android distribution channels and dynamic linking to the .so is fulfilling your obligation to the license. If you really feel like it's going to be an issue you can distribute an unsigned apk that people can rezip with the .so of their choice.

**Comment by dertom95** [comment]
Hmm,..ok! Thx for your fast reply. Still not totally convinced... :D  
But nevertheless thx a lot

**Comment by alexcohn** [comment]
It is possible to prepare your APK with `libopenal.so` being unpacked to a public folder, and let the user replace it. You will only need to use `System.load(fullPathToPublicFolder + "/libopenal.so")` in your Java.

But in terms of LGPL, it's OK IMHO to expect the users to have root access to their device.
